---
title: "Broken Windows Investigation Replication Package"
author: Hampus Broman & William Levén
date: 2021-05
output: 
  html_document: 
    pandoc_args: [ "-o", "docs/index.html" ]
    toc: no
---
This is a replication package for the *Broken Windows Investigation* thesis conducted by [Hampus Broman](https://github.com/HBroman) and [William Levén](https://github.com/williamleven) in 2021.

The package contains a presentation as well as the [source](https://github.com/BrokenWindowsInvestigation/Analysis) for the whole analysis performed.

Read the Broken Windows Investigation thesis for more information and justification about the analysis and procedure.

## Notes

If you have any questions or feel that anything in the replication package is amiss, please [open an issue](https://github.com/BrokenWindowsInvestigation/Analysis/issues).

1. Most models have been run with moment matching to improve pareto-k diagnostics. We found no consistent errors in the loo estimates and did not include the moment matching in the replication package due its resource intensiveness.
2. Seeds have been used where possible to reduce the effects of randomness for those who wish to execute this replication package themselves. All steps does however not support seeding (especially loo and posterior sampling) and may therefore produce slightly different results on each execution. Seeds were selected as the date of the day they were introduced on.

## Sub pages:

* [Overview](index.html) - Provides an overview if the replication package.
* [Setup](setup.html) - Data preparation, utility function and library imports.
* [Data description](data_description.html) - Plots and data descriptions not relating to the outcomes, those are found in "Baysian Models".
* Models - All our models grouped by which outcome they measure.
  * [Logic reuse](logic_reuse.html) - Exploration and models related to code reuse.
  * [Variable naming](variable_naming.html) - Exploration and models related to variable naming.
  * [Sonarqube issues](sonarqube_issues.html) - Exploration and models related to introduced sonarqube issues.
  * [Implemented utility methods](implemented_utility_methods.html) - Exploration and models related to the implementation of utility methods.
  * [Documentation state](documentation_state.html) - Exploration and models related to the state of the validation documentation.
  * [Task completion](task_completion.html) - Exploration and models related to dropouts and task completion.
  * [Time to complete task](time_to_complete_task.html) - Exploration and models related to the time outcome.
  * [System quality rating](system_quality_rating.html) - Exploration and models related how participants rathed the quality of the scenario.
  * [Self-reported submission quality](self-reported_submission_quality.html) - Exploration and models related to how participants reported the quality of their own work.
* [Environment](environment.html) - Description of the computational environment used to perform the analysis.