---
title: "Reuse"
output: html_notebook
---

Some plots of the data:

```{r}
d.completed %>%
  ggplot(aes(high_debt_version)) +
  geom_bar(aes(fill = reused_logic_constructor), position = "fill") + 
  scale_fill_manual("legend", values = c("true" = "green", "false" = "red")) +
  labs(title = "Constructor Reuse") +
  xlab("High Debt version") +
  ylab("Ratio of reuse")

d.completed %>%
  ggplot(aes(high_debt_version)) +
  geom_bar(aes(fill = reused_logic_validation), position = "fill") + 
  scale_fill_manual("legend", values = c("true" = "green", "false" = "red")) +
  labs(title = "Validation Reuse") +
  xlab("High Debt version") +
  ylab("Ratio of reuse")

d.completed %>%
  filter(has_equals == "true") %>%
  ggplot(aes(high_debt_version)) +
  geom_bar(aes(fill = reused_logic_equals), position = "fill") + 
  scale_fill_manual("legend", values = c("true" = "green", "false" = "red")) +
  labs(title = "Equals Reuse") +
  xlab("High Debt version") +
  ylab("Ratio of reuse")

d.completed %>%
  filter(has_hashcode == "true") %>%
  ggplot(aes(high_debt_version)) +
  geom_bar(aes(fill = reused_logic_hashcode), position = "fill") + 
  scale_fill_manual("legend", values = c("true" = "green", "false" = "red")) +
  labs(title = "HashCode Reuse") +
  xlab("High Debt version") +
  ylab("Ratio of reuse")

```

Initial model:
```{r}
reuse0 <- brm(
  mvbind(
    reused_logic_validation,
    reused_logic_constructor
  ) ~ 1
  + high_debt_version
  + (1 | c | session),
  family = bernoulli(),
  data = as.data.frame(d.completed),
  prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(0, 1), class = "Intercept"),
    prior(exponential(1), class = "sd", resp = reusedlogicconstructor),
    prior(exponential(1), class = "sd", resp = reusedlogicvalidation),
    prior(lkj(2), class = "L")
  ),
  # empty = TRUE, # If you only want to check prior definitions
  # sample_prior = "only",
  backend = "cmdstan",
  chains = 4,
  cores = 4,
  iter = 5e3,
  file = "fits/reuse0",
  file_refit = "on_change"
)

summary(reuse0)
```


```{r}
reuse1_scenario <- brm(
  mvbind(
    reused_logic_validation,
    reused_logic_constructor
  ) ~ 1
  + high_debt_version
  + scenario
  + (1 | c | session),
  family = bernoulli(),
  data = as.data.frame(d.completed),
  prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(0, 1), class = "Intercept"),
    prior(exponential(1), class = "sd", resp = reusedlogicconstructor),
    prior(exponential(1), class = "sd", resp = reusedlogicvalidation),
    prior(lkj(2), class = "L")
  ),
  # empty = TRUE, # If you only want to check prior definitions
  # sample_prior = "only",
  backend = "rstan",
  chains = 4,
  cores = 4,
  iter = 5e3,
  file = "fits/reuse1_scenario",
  file_refit = "on_change"
)

summary(reuse1_scenario)
```

```{r}
reuse1_experience_programming <- brm(
  mvbind(
    reused_logic_validation,
    reused_logic_constructor
  ) ~ 1
  + high_debt_version
  + work_experience_programming.s
  + (1 | c | session),
  family = bernoulli(),
  data = as.data.frame(d.completed),
  prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(0, 1), class = "Intercept"),
    prior(exponential(1), class = "sd", resp = reusedlogicconstructor),
    prior(exponential(1), class = "sd", resp = reusedlogicvalidation),
    prior(lkj(2), class = "L")
  ),
  # empty = TRUE, # If you only want to check prior definitions
  # sample_prior = "only",
  backend = "rstan",
  chains = 4,
  cores = 4,
  iter = 5e3,
  file = "fits/reuse1_experience_programming",
  file_refit = "on_change"
)

summary(reuse1_experience_programming)
```


```{r}
reuse1_experience_java <- brm(
  mvbind(
    reused_logic_validation,
    reused_logic_constructor
  ) ~ 1
  + high_debt_version
  + work_experience_java.s
  + (1 | c | session),
  family = bernoulli(),
  data = as.data.frame(d.completed),
  prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(0, 1), class = "Intercept"),
    prior(exponential(1), class = "sd", resp = reusedlogicconstructor),
    prior(exponential(1), class = "sd", resp = reusedlogicvalidation),
    prior(lkj(2), class = "L")
  ),
  # empty = TRUE, # If you only want to check prior definitions
  # sample_prior = "only",
  backend = "rstan",
  chains = 4,
  cores = 4,
  iter = 5e3,
  file = "fits/reuse1_experience_java",
  file_refit = "on_change"
)

summary(reuse1_experience_java)
```

```{r}
reuse1_education_field <- brm(
  mvbind(
    reused_logic_validation,
    reused_logic_constructor
  ) ~ 1
  + high_debt_version
  + education_field
  + (1 | c | session),
  family = bernoulli(),
  data = as.data.frame(d.completed),
  prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(0, 1), class = "Intercept"),
    prior(exponential(1), class = "sd", resp = reusedlogicconstructor),
    prior(exponential(1), class = "sd", resp = reusedlogicvalidation),
    prior(lkj(2), class = "L")
  ),
  # empty = TRUE, # If you only want to check prior definitions
  # sample_prior = "only",
  backend = "rstan",
  chains = 4,
  cores = 4,
  iter = 5e3,
  file = "fits/reuse1_education_field",
  file_refit = "on_change"
)

summary(reuse1_education_field)
```


```{r}
reuse1_education_level <- brm(
  mvbind(
    reused_logic_validation,
    reused_logic_constructor
  ) ~ 1
  + high_debt_version
  + mo(education_level)
  + (1 | c | session),
  family = bernoulli(),
  data = as.data.frame(d.completed),
  prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(0, 1), class = "Intercept"),
    prior(exponential(1), class = "sd", resp = reusedlogicconstructor),
    prior(exponential(1), class = "sd", resp = reusedlogicvalidation),
    prior(dirichlet(2), class = "simo", coef = "moeducation_level1", resp = reusedlogicconstructor),
    prior(dirichlet(2), class = "simo", coef = "moeducation_level1", resp = reusedlogicvalidation),
    prior(lkj(2), class = "L")
  ),
  # empty = TRUE, # If you only want to check prior definitions
  # sample_prior = "only",
  backend = "rstan",
  chains = 4,
  cores = 4,
  iter = 5e3,
  file = "fits/reuse1_education_level",
  file_refit = "on_change"
)

summary(reuse1_education_level)
```




```{r}
reuse1_workplace_peer_review <- brm(
  mvbind(
    reused_logic_validation,
    reused_logic_constructor
  ) ~ 1
  + high_debt_version
  + workplace_peer_review
  + (1 | c | session),
  family = bernoulli(),
  data = as.data.frame(d.completed),
  prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(0, 1), class = "Intercept"),
    prior(exponential(1), class = "sd", resp = reusedlogicconstructor),
    prior(exponential(1), class = "sd", resp = reusedlogicvalidation),
    prior(lkj(2), class = "L")
  ),
  # empty = TRUE, # If you only want to check prior definitions
  # sample_prior = "only",
  backend = "rstan",
  chains = 4,
  cores = 4,
  iter = 5e3,
  file = "fits/reuse1_workplace_peer_review",
  file_refit = "on_change"
)

summary(reuse1_workplace_peer_review)
```

```{r}
reuse1_workplace_td_tracking <- brm(
  mvbind(
    reused_logic_validation,
    reused_logic_constructor
  ) ~ 1
  + high_debt_version
  + workplace_td_tracking
  + (1 | c | session),
  family = bernoulli(),
  data = as.data.frame(d.completed),
  prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(0, 1), class = "Intercept"),
    prior(exponential(1), class = "sd", resp = reusedlogicconstructor),
    prior(exponential(1), class = "sd", resp = reusedlogicvalidation),
    prior(lkj(2), class = "L")
  ),
  # empty = TRUE, # If you only want to check prior definitions
  # sample_prior = "only",
  backend = "rstan",
  chains = 4,
  cores = 4,
  iter = 5e3,
  file = "fits/reuse1_workplace_td_tracking",
  file_refit = "on_change"
)

summary(reuse1_workplace_td_tracking)
```

```{r}
reuse1_workplace_pair_programming <- brm(
  mvbind(
    reused_logic_validation,
    reused_logic_constructor
  ) ~ 1
  + high_debt_version
  + workplace_pair_programming
  + (1 | c | session),
  family = bernoulli(),
  data = as.data.frame(d.completed),
  prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(0, 1), class = "Intercept"),
    prior(exponential(1), class = "sd", resp = reusedlogicconstructor),
    prior(exponential(1), class = "sd", resp = reusedlogicvalidation),
    prior(lkj(2), class = "L")
  ),
  # empty = TRUE, # If you only want to check prior definitions
  # sample_prior = "only",
  backend = "rstan",
  chains = 4,
  cores = 4,
  iter = 5e3,
  file = "fits/reuse1_workplace_pair_programming",
  file_refit = "on_change"
)

summary(reuse1_workplace_pair_programming)
```

```{r}
reuse1_workplace_coding_standards <- brm(
  mvbind(
    reused_logic_validation,
    reused_logic_constructor
  ) ~ 1
  + high_debt_version
  + workplace_coding_standards
  + (1 | c | session),
  family = bernoulli(),
  data = as.data.frame(d.completed),
  prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(0, 1), class = "Intercept"),
    prior(exponential(1), class = "sd", resp = reusedlogicconstructor),
    prior(exponential(1), class = "sd", resp = reusedlogicvalidation),
    prior(lkj(2), class = "L")
  ),
  # empty = TRUE, # If you only want to check prior definitions
  # sample_prior = "only",
  backend = "rstan",
  chains = 4,
  cores = 4,
  iter = 5e3,
  file = "fits/reuse1_workplace_coding_standards",
  file_refit = "on_change"
)

summary(reuse1_workplace_coding_standards)
```


```{r}
reuse1_work_domain <- brm(
  mvbind(
    reused_logic_validation,
    reused_logic_constructor
  ) ~ 1
  + high_debt_version
  + work_domain
  + (1 | c | session),
  family = bernoulli(),
  data = as.data.frame(d.completed),
  prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(0, 1), class = "Intercept"),
    prior(exponential(1), class = "sd", resp = reusedlogicconstructor),
    prior(exponential(1), class = "sd", resp = reusedlogicvalidation),
    prior(lkj(2), class = "L")
  ),
  # empty = TRUE, # If you only want to check prior definitions
  # sample_prior = "only",
  backend = "rstan",
  chains = 4,
  cores = 4,
  iter = 5e3,
  file = "fits/reuse1_work_domain",
  file_refit = "on_change"
)

summary(reuse1_work_domain)
```

```{r}
reuse1_group <- brm(
  mvbind(
    reused_logic_validation,
    reused_logic_constructor
  ) ~ 1
  + high_debt_version
  + group
  + (1 | c | session),
  family = bernoulli(),
  data = as.data.frame(d.completed),
  prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(0, 1), class = "Intercept"),
    prior(exponential(1), class = "sd", resp = reusedlogicconstructor),
    prior(exponential(1), class = "sd", resp = reusedlogicvalidation),
    prior(lkj(2), class = "L")
  ),
  # empty = TRUE, # If you only want to check prior definitions
  # sample_prior = "only",
  backend = "rstan",
  chains = 4,
  cores = 4,
  iter = 5e3,
  file = "fits/reuse1_group",
  file_refit = "on_change"
)

summary(reuse1_group)
```

```{r}
loo(
  reuse1_group,
  reuse1_work_domain,
  reuse1_workplace_coding_standards,
  reuse1_workplace_pair_programming,
  reuse1_workplace_td_tracking,
  reuse1_workplace_peer_review,
  reuse1_education_level,
  reuse1_education_field,
  reuse1_experience_java,
  reuse1_experience_programming,
  reuse1_scenario,
  reuse0
)

```



```{r}
reuse2_all <- brm(
  mvbind(
    reused_logic_validation,
    reused_logic_constructor
  ) ~ 1
  + high_debt_version
  + workplace_peer_review
  + workplace_td_tracking
  + mo(education_level)
  + (1 | c | session),
  family = bernoulli(),
  data = as.data.frame(d.completed),
  prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(0, 1), class = "Intercept"),
    prior(exponential(1), class = "sd", resp = reusedlogicconstructor),
    prior(exponential(1), class = "sd", resp = reusedlogicvalidation),
    prior(dirichlet(2), class = "simo", coef = "moeducation_level1", resp = reusedlogicconstructor),
    prior(dirichlet(2), class = "simo", coef = "moeducation_level1", resp = reusedlogicvalidation),
    prior(lkj(2), class = "L")
  ),
  # empty = TRUE, # If you only want to check prior definitions
  # sample_prior = "only",
  backend = "cmdstan",
  chains = 4,
  cores = 4,
  iter = 5e3,
  file = "fits/reuse2_all",
  file_refit = "on_change"
)

summary(reuse2_all)
```

```{r}
reuse2_no_education_level <- brm(
  mvbind(
    reused_logic_validation,
    reused_logic_constructor
  ) ~ 1
  + high_debt_version
  + workplace_peer_review
  + workplace_td_tracking
  + (1 | c | session),
  family = bernoulli(),
  data = as.data.frame(d.completed),
  prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(0, 1), class = "Intercept"),
    prior(exponential(1), class = "sd", resp = reusedlogicconstructor),
    prior(exponential(1), class = "sd", resp = reusedlogicvalidation),
    prior(lkj(2), class = "L")
  ),
  # empty = TRUE, # If you only want to check prior definitions
  # sample_prior = "only",
  backend = "cmdstan",
  chains = 4,
  cores = 4,
  iter = 5e3,
  file = "fits/reuse2_no_education_level",
  file_refit = "on_change"
)

summary(reuse2_no_education_level)
```


```{r}
reuse2_no_workplace_td_tracking <- brm(
  mvbind(
    reused_logic_validation,
    reused_logic_constructor
  ) ~ 1
  + high_debt_version
  + workplace_peer_review
  + mo(education_level)
  + (1 | c | session),
  family = bernoulli(),
  data = as.data.frame(d.completed),
  prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(0, 1), class = "Intercept"),
    prior(exponential(1), class = "sd", resp = reusedlogicconstructor),
    prior(exponential(1), class = "sd", resp = reusedlogicvalidation),
    prior(dirichlet(2), class = "simo", coef = "moeducation_level1", resp = reusedlogicconstructor),
    prior(dirichlet(2), class = "simo", coef = "moeducation_level1", resp = reusedlogicvalidation),
    prior(lkj(2), class = "L")
  ),
  # empty = TRUE, # If you only want to check prior definitions
  # sample_prior = "only",
  backend = "cmdstan",
  chains = 4,
  cores = 4,
  iter = 5e3,
  file = "fits/reuse2_no_workplace_td_tracking",
  file_refit = "on_change"
)

summary(reuse2_no_workplace_td_tracking)
```

```{r}
reuse2_no_workplace_peer_review <- brm(
  mvbind(
    reused_logic_validation,
    reused_logic_constructor
  ) ~ 1
  + high_debt_version
  + workplace_td_tracking
  + mo(education_level)
  + (1 | c | session),
  family = bernoulli(),
  data = as.data.frame(d.completed),
  prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(0, 1), class = "Intercept"),
    prior(exponential(1), class = "sd", resp = reusedlogicconstructor),
    prior(exponential(1), class = "sd", resp = reusedlogicvalidation),
    prior(dirichlet(2), class = "simo", coef = "moeducation_level1", resp = reusedlogicconstructor),
    prior(dirichlet(2), class = "simo", coef = "moeducation_level1", resp = reusedlogicvalidation),
    prior(lkj(2), class = "L")
  ),
  # empty = TRUE, # If you only want to check prior definitions
  # sample_prior = "only",
  backend = "cmdstan",
  chains = 4,
  cores = 4,
  iter = 5e3,
  file = "fits/reuse2_no_workplace_peer_review",
  file_refit = "on_change"
)

summary(reuse2_no_workplace_peer_review)
```


```{r}
loo(
  reuse1_workplace_td_tracking,
  reuse1_workplace_peer_review,
  reuse1_education_level,
  reuse2_no_workplace_td_tracking,
  reuse2_no_workplace_peer_review,
  reuse2_no_education_level,
  reuse0,
  reuse2_all
)

```







