---
title: "Variable Names"
output: html_notebook
---

Variable names:

```{r}

d.completed %>%
  ggplot(aes(x=var_names_new_good.ratio, fill=high_debt_version)) + 
  geom_boxplot()

d.completed %>%
  filter(!is.nan(var_names_copied_good.ratio)) %>%
  ggplot(aes(x=var_names_copied_good.ratio, fill=high_debt_version)) + 
  geom_boxplot()


mean(d.completed$var_names_new_good)
var(d.completed$var_names_new_good)
```



Basic model with binomial distribution:

```{r}
var_names0 <- brm(
  var_names_new_good | trials(var_names_new_all) ~ 1
  + high_debt_version
  + (1 | session),
  family = binomial(),
  data = as.data.frame(d.completed),
    prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(2, 1), class = "Intercept"),
    prior(exponential(1), class = "sd")
  ),
  control = list(adapt_delta = 0.95),
  backend = "cmdstanr",
  chains = 4,
  cores = 4,
  iter = 5e3,
  #empty = TRUE,
  #sample_prior = "only",
  file = "fits/var_names0",
  file_refit = "on_change"
)

#pp_check(var_names0, type="bars", nsamples=100)
summary(var_names0)

```

```{r}
var_names1_education_level <- brm(
  var_names_new_good | trials(var_names_new_all) ~ 1
  + high_debt_version
  + mo(education_level)
  + (1 | session),
  family = binomial(),
  data = as.data.frame(d.completed),
    prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(2, 1), class = "Intercept"),
    prior(exponential(1), class = "sd")
  ),
  control = list(adapt_delta = 0.95),
  backend = "cmdstanr",
  chains = 4,
  cores = 4,
  iter = 5e3,
  #empty = TRUE
  #sample_prior = "only",
  file = "fits/var_names1_education_level",
  file_refit = "on_change"
)

#pp_check(var_names1_education_level, type="bars", nsamples=100)
summary(var_names1_education_level)

```

```{r}
var_names1_education_field <- brm(
  var_names_new_good | trials(var_names_new_all) ~ 1
  + high_debt_version
  + (1 | session)
  + education_field,
  family = binomial(),
  data = as.data.frame(d.completed),
    prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(2, 1), class = "Intercept"),
    prior(exponential(1), class = "sd")
  ),
  control = list(adapt_delta = 0.95),
  backend = "cmdstanr",
  chains = 4,
  cores = 4,
  iter = 5e3,
  #empty = TRUE
  #sample_prior = "only",
  file = "fits/var_names1_education_field",
  file_refit = "on_change"
)

summary(var_names1_education_field)

```

```{r}
var_names1_work_domain <- brm(
  var_names_new_good | trials(var_names_new_all) ~ 1
  + high_debt_version
  + work_domain
  + (1 | session),
  family = binomial(),
  data = as.data.frame(d.completed),
    prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(2, 1), class = "Intercept"),
    prior(exponential(1), class = "sd")
  ),
  control = list(adapt_delta = 0.95),
  backend = "cmdstanr",
  chains = 4,
  cores = 4,
  iter = 5e3,
  #empty = TRUE
  #sample_prior = "only",
  file = "fits/var_names1_work_domain",
  file_refit = "on_change"
)

summary(var_names1_work_domain)

```

```{r}
var_names1_exp <- brm(
  var_names_new_good | trials(var_names_new_all) ~ 1
  + high_debt_version
  + work_experience_programming.s
  + (1 | session),
  family = binomial(),
  data = as.data.frame(d.completed),
    prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(2, 1), class = "Intercept"),
    prior(exponential(1), class = "sd")
  ),
  control = list(adapt_delta = 0.95),
  backend = "cmdstanr",
  chains = 4,
  cores = 4,
  iter = 5e3,
  #empty = TRUE
  #sample_prior = "only",
  file = "fits/var_names1_exp",
  file_refit = "on_change"
)

summary(var_names1_exp)

```

```{r}
var_names1_java <- brm(
  var_names_new_good | trials(var_names_new_all) ~ 1
  + high_debt_version
  + work_experience_java.s
  + (1 | session),
  family = binomial(),
  data = as.data.frame(d.completed),
    prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(2, 1), class = "Intercept"),
    prior(exponential(1), class = "sd")
  ),
  control = list(adapt_delta = 0.95),
  backend = "cmdstanr",
  chains = 4,
  cores = 4,
  iter = 5e3,
  #empty = TRUE
  #sample_prior = "only",
  file = "fits/var_names1_java",
  file_refit = "on_change"
)

summary(var_names1_java)

```


```{r}
var_names1_practice_peer_review <- brm(
  var_names_new_good | trials(var_names_new_all) ~ 1
  + high_debt_version
  + + workplace_peer_review
  + (1 | session),
  family = binomial(),
  data = as.data.frame(d.completed),
    prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(2, 1), class = "Intercept"),
    prior(exponential(1), class = "sd")
  ),
  control = list(adapt_delta = 0.95),
  backend = "cmdstanr",
  chains = 4,
  cores = 4,
  iter = 5e3,
  #empty = TRUE
  #sample_prior = "only",
  file = "fits/var_names1_practice_peer_review",
  file_refit = "on_change"
)

summary(var_names1_practice_peer_review)

```

```{r}
var_names1_practice_td_tracking <- brm(
  var_names_new_good | trials(var_names_new_all) ~ 1
  + high_debt_version
  + + workplace_td_tracking
  + (1 | session),
  family = binomial(),
  data = as.data.frame(d.completed),
    prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(2, 1), class = "Intercept"),
    prior(exponential(1), class = "sd")
  ),
  control = list(adapt_delta = 0.95),
  backend = "cmdstanr",
  chains = 4,
  cores = 4,
  iter = 5e3,
  #empty = TRUE
  #sample_prior = "only",
  file = "fits/var_names1_practice_td_tracking",
  file_refit = "on_change"
)

summary(var_names1_practice_td_tracking)

```



```{r}
var_names1_practice_pair_programming <- brm(
  var_names_new_good | trials(var_names_new_all) ~ 1
  + high_debt_version
  + + workplace_pair_programming
  + (1 | session),
  family = binomial(),
  data = as.data.frame(d.completed),
    prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(2, 1), class = "Intercept"),
    prior(exponential(1), class = "sd")
  ),
  control = list(adapt_delta = 0.95),
  backend = "cmdstanr",
  chains = 4,
  cores = 4,
  iter = 5e3,
  #empty = TRUE
  #sample_prior = "only",
  file = "fits/var_names1_practice_pair_programming",
  file_refit = "on_change"
)

summary(var_names1_practice_pair_programming)

```



```{r}
var_names1_practice_coding_standards <- brm(
  var_names_new_good | trials(var_names_new_all) ~ 1
  + high_debt_version
  + workplace_coding_standards
  + (1 | session),
  family = binomial(),
  data = as.data.frame(d.completed),
    prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(2, 1), class = "Intercept"),
    prior(exponential(1), class = "sd")
  ),
  control = list(adapt_delta = 0.95),
  backend = "cmdstanr",
  chains = 4,
  cores = 4,
  iter = 5e3,
  #empty = TRUE
  #sample_prior = "only",
  file = "fits/var_names1_practice_coding_standards",
  file_refit = "on_change"
)

summary(var_names1_practice_coding_standards)

```


```{r}
var_names1_scenario <- brm(
  var_names_new_good | trials(var_names_new_all) ~ 1
  + high_debt_version
  + scenario
  + (1 | session),
  family = binomial(),
  data = as.data.frame(d.completed),
    prior = c(
    prior(normal(0, 1), class = "b"),
    prior(normal(2, 1), class = "Intercept"),
    prior(exponential(1), class = "sd")
  ),
  control = list(adapt_delta = 0.95),
  backend = "cmdstanr",
  chains = 4,
  cores = 4,
  iter = 5e3,
  #empty = TRUE
  #sample_prior = "only",
  file = "fits/var_names1_scenario",
  file_refit = "on_change"
)

summary(var_names1_scenario)

```

```{r}
loo(
  var_names0,
  var_names1_exp,
  var_names1_java,
  var_names1_education_field,
  var_names1_education_level,
  var_names1_practice_peer_review,
  var_names1_practice_td_tracking,
  var_names1_practice_pair_programming,
  var_names1_practice_coding_standards,
  var_names1_scenario,
  #var_names1_group,
  var_names1_work_domain
)

```


```{r}
# Sample model example
sample <- posterior_predict(var_names0, newdata = data.frame(high_debt_version = "false", var_names_new_all = 10), re_formula = NA)
```